portals: []
    
parkour:
  start: 'x,y,z,yaw,pitch'
  checkpoints:
  - 'x,y,z,yaw,pitch'
  finish: 'x,y,z,yaw,pitch'
  allow-touch: []
  
allow-interact:
- OAK_BUTTON
- SPRUCE_BUTTON
- BIRCH_BUTTON
- DARK_OAK_BUTTON
- ACACIA_BUTTON
- JUNGLE_BUTTON

launchpad-power: 5
launchpad-angle: -10.0
  
bossbar:
  rate: 0.5
  text:
  - '&6FACT Minecraft Network'
  - '&2FACT Minecraft Network'
  - '&5FACT Minecraft Network'
  color:
  - 'YELLOW'
  - 'GREEN'
  - 'PURPLE'
  style: SEGMENTED_10
  
sidebar:
  rate: 0.2
  title: 'Welcome %name%'
  first-color: 'YELLOW'
  second-color: 'GREEN'
  lines:
  - ''
  - 'Rank: %rank%'
  - '&r'
  - 'Points: &e%points%'
  - 'Total Votes: &b%votes%'
  - '&r&r'
  - 'Current Time: &d%time%'
  - '&r&r&r'
  - '&2https://factmc.net/'