name: FactHub
main: net.factmc.FactHub.Main
version: 2.5
author: TrollyLoki
depend: [LuckPerms, FactCore, FactBukkit]
soft-depend: [SuperVanish, FactCosmetics]

api-version: 1.14

commands:
  facthub:
    aliases: [fhub, fh]

  servers:
  
  parkour:
    aliases: p
  vote:
  
permissions:
  facthub.reload:
    default: op
  
  facthub.use:
    description: Allows you to interact with things in the hub
    default: op
    
  facthub.escape:
    default: op
  facthub.oxygen:
    default: false