name: ${project.artifactId}
main: ${project.groupId}.Main
version: ${project.version}
author: TrollyLoki
depend: [LuckPerms, FactCore, FactBukkit]
soft-depend: [SuperVanish, FactCosmetics]

api-version: 1.15

commands:
  facthub:
    aliases: [fhub, fh]
  
  parkour:
    aliases: p
  
permissions:
  facthub.reload:
    default: op
  
  facthub.use:
    description: Allows you to interact with things in the hub
    default: op
    
  facthub.escape:
    default: op
  facthub.oxygen:
    default: false